version: 2

models:
  - name: mart_registrations_by_year
    columns:
      - name: registration_year
        tests:
          - unique
          - not_null

  - name: mart_registrations_by_company_type
    columns:
      - name: company_type
        tests:
          - unique
          - not_null

  - name: mart_credit_by_area
    columns:
      - name: area
        tests:
          - unique
          - not_null